version: "3.7"
services:
  myweb:
    build:
      context: .
      args:
        whoami: "Tony"
    image: uopsdod/myweb:latest
    ports:
      - "8080:80"  
    networks:
      - mybridge001
  myweb2:
    build:
      context: .
      args:
        whoami: "Chris"
    image: uopsdod/myweb1:latest
    ports:
      - "8081:80"  
    networks:
      - mybridge001
  myweb3:
    build:
      context: .
      args:
        whoami: "Jane"
    image: uopsdod/myweb2:latest
    ports:
      - "8082:80"  
    networks:
      - mybridge001
  myweb4:
    image: uopsdod/myweb:latest
    ports:
      - "8083:80"  
    networks:
      - mybridge002
  myweb5:
    image: uopsdod/myweb:latest
    ports:
      - "8084:80"  
    networks:
      - mybridge002
    volumes:
      - mainpage-vol002:/var/www/localhost/htdocs/


networks:
  mybridge001:
  mybridge002:

volumes:
  mainpage-vol002:






